name: Ruby

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/set-timezone-action@v1.1
      with:
        timezoneLinux: America/Sao_Paulo
  timezoneLinux: "Asia/Singapore"
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    - name: Run the default task
      run: |
        gem install bundler -v 2.2.9
        bundle install
        bundle exec rake
 
    - name: Run tests
      run: rspec
